# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\"\xb1\x01\n\tAiRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x39\n\nparameters\x18\x03 \x03(\x0b\x32%.ai_service.AiRequest.ParametersEntry\x12\x12\n\nagent_type\x18\x04 \x01(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xab\x01\n\nAiResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x36\n\x08metadata\x18\x03 \x03(\x0b\x32$.ai_service.AiResponse.MetadataEntry\x12\x0e\n\x06status\x18\x04 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\rStreamRequest\x12\x12\n\nagent_type\x18\x01 \x01(\t\x12\x0e\n\x06topics\x18\x02 \x03(\t\"\x94\x01\n\x07\x41iEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x33\n\x08metadata\x18\x03 \x03(\x0b\x32!.ai_service.AiEvent.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x8e\x01\n\tAiService\x12?\n\x0eProcessMessage\x12\x15.ai_service.AiRequest\x1a\x16.ai_service.AiResponse\x12@\n\x0cStreamEvents\x12\x19.ai_service.StreamRequest\x1a\x13.ai_service.AiEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_AIREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_AIRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_AIRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AIEVENT_METADATAENTRY']._loaded_options = None
  _globals['_AIEVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AIREQUEST']._serialized_start=33
  _globals['_AIREQUEST']._serialized_end=210
  _globals['_AIREQUEST_PARAMETERSENTRY']._serialized_start=161
  _globals['_AIREQUEST_PARAMETERSENTRY']._serialized_end=210
  _globals['_AIRESPONSE']._serialized_start=213
  _globals['_AIRESPONSE']._serialized_end=384
  _globals['_AIRESPONSE_METADATAENTRY']._serialized_start=337
  _globals['_AIRESPONSE_METADATAENTRY']._serialized_end=384
  _globals['_STREAMREQUEST']._serialized_start=386
  _globals['_STREAMREQUEST']._serialized_end=437
  _globals['_AIEVENT']._serialized_start=440
  _globals['_AIEVENT']._serialized_end=588
  _globals['_AIEVENT_METADATAENTRY']._serialized_start=337
  _globals['_AIEVENT_METADATAENTRY']._serialized_end=384
  _globals['_AISERVICE']._serialized_start=591
  _globals['_AISERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
